# This is a basic workflow to help you get started with Actions

name: forgepush

# We just want to run this manually. 
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Publish
        run: |
          cd $GITHUB_WORKSPACE
          wget https://raw.githubusercontent.com/tmg-pub/forgepush/main/forgepush.py
          py forgepush.py --apitoken ${{secrets.forgetoken}}
